name: gaz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.49382440419867635
  saturation: 0.7211326330434531
  rhythmicContrast: 0.35295728128403425
purpose: []
